// Writes ../FlowWise.html — the app itself, with no data in it — and the data files it reads.
// The app loads its data from a separate script file:
//   data/flowwise-real.js  — real bank and card data (personal, git-ignored)      built by build.mjs
//   demo/flowwise-demo.js  — invented demo data (safe to share and submit)       built by build-demo.mjs
// Which one FlowWise.html reads is set with:  node standalone/use-data.mjs real | demo
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
export const root = path.resolve(here, "..");
export const APP = path.join(root, "FlowWise.html");
export const DATA_FILES = { real: "data/flowwise-real.js", demo: "demo/flowwise-demo.js" };
const TAG = /<script src="([^"]*)" id="flowwise-data"><\/script>/;

const json = (o) => JSON.stringify(o).replace(/</g, "\\u003c");

/** Which data file FlowWise.html currently reads ("real" / "demo"), or null. */
export function currentData() {
  if (!fs.existsSync(APP)) return null;
  const src = TAG.exec(fs.readFileSync(APP, "utf8"))?.[1];
  return Object.entries(DATA_FILES).find(([, f]) => f === src)?.[0] ?? null;
}

/** Writes one data file: window.FLOWWISE_DATA = {...}. */
export function writeData(which, data) {
  const file = path.join(root, DATA_FILES[which]);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `// FlowWise ${which === "demo" ? "demo (invented) data" : "real data — personal, do not share"}. Generated by standalone/${which === "demo" ? "build-demo" : "build"}.mjs.\nwindow.FLOWWISE_DATA = ${json(data)};\n`);
  return file;
}

/** Rebuilds FlowWise.html (or `out`) from template.html. Keeps the data file it already points to unless `which` is given. */
export function writeApp(which = currentData() ?? "real", out = APP) {
  let prdSrc = fs.readFileSync(path.join(root, "code", "src", "data", "prd.ts"), "utf8");
  prdSrc = prdSrc.slice(prdSrc.indexOf("export const prdMeta")).replace(/export const /g, "const ")
    .replace(/sections\s*:\s*Section\[\]/, "sections").replace(/\bprd\w+\.url\b/g, '""');
  const { prdMeta, sections } = new Function(`${prdSrc}\nreturn { prdMeta, sections };`)();
  for (const s of sections) s.blocks = s.blocks.filter((b) => b.t !== "img"); // screenshots were hosted by Lovable

  let html = fs.readFileSync(path.join(here, "template.html"), "utf8");
  if (!TAG.test(html)) throw new Error("template.html: data <script> tag not found");
  html = html.replace(TAG, `<script src="${DATA_FILES[which]}" id="flowwise-data"></script>`)
    .replace("/*__PRD__*/null", () => json({ prdMeta, sections }));
  fs.writeFileSync(out, html);
  return { which, file: DATA_FILES[which], sections: sections.length };
}
